if(playerPrestlap1 == 0)
image_index = 0
if(playerPrestlap1 == 1)
image_index = 1
if(playerPrestlap1 == 2)
image_index = 2
if(playerPrestlap1 == 3)
image_index = 3
if(playerPrestlap1 == 4)
image_index = 4
if(playerPrestlap1 == 5)
image_index = 5
if(playerPrestlap1 == 6)
image_index = 6
if(playerPrestlap1 == 7)
image_index = 7
if(playerPrestlap1 = 8)
image_index = 8
if(playerPrestlap1 == 9)
image_index = 9
if(playerPrestlap1 == 10)
image_index = 10