if(playerErestlap1 == 0)
image_index = 0
if(playerErestlap1 == 1)
image_index = 1
if(playerErestlap1 == 2)
image_index = 2
if(playerErestlap1 == 3)
image_index = 3
if(playerErestlap1 == 4)
image_index = 4
if(playerErestlap1 == 5)
image_index = 5
if(playerErestlap1 == 6)
image_index = 6
if(playerErestlap1 == 7)
image_index = 7