if(playerHrestlap1 == 0)
image_index = 0
if(playerHrestlap1 == 1)
image_index = 1
if(playerHrestlap1 == 2)
image_index = 2
if(playerHrestlap1 == 3)
image_index = 3
if(playerHrestlap1 == 4)
image_index = 4
if(playerHrestlap1 == 5)
image_index = 5
if(playerHrestlap1 == 6)
image_index = 6
if(playerHrestlap1 = 7)
image_index = 7